### PR TITLE
Add charts for the Apisonator Internal API

### PR DESCRIPTION
**Pull request by davidor**
This PR adds charts for the Apisonator Internal API.

I know I have to run `make assets` but it's giving me an error because it can't download one of the dependencies. Not sure if it's a temporary issue.

### CODE REVIEW

**Comment by eguzki** [comment]
I wish it was a temporary issue. One of the indirect dependencies is gone. bitbucket.org/ww/goautoneg

We are working on this issue and once we merge to master, you will need to rebase to pass all the checks

**Comment by eguzki** [comment]
PR sent to fix the missing dep: https://github.com/3scale/3scale-operator/pull/475

**Comment by eguzki** [comment]
rebase and run `make assets` to embed the changes of the templates in the compiled binary.

**Comment by davidor** [comment]
I've rebased and run `make assets`.

**Comment by eguzki** [comment]
Dashboard of 10k lines

#GodSaveUs

**Review by eguzki — APPROVED** [review]

**Pull request merged**
