### PR TITLE
toc-test

### PR DESCRIPTION
**Pull request by austincunningham**
Fix failing toc check

### CODE REVIEW

**Comment by austincunningham** [comment]
tied to 0.8.0

**Comment by MStokluska** [comment]
/lgtm

Until we get a new release of github markdown toc we can use master version.

**Comment by eguzki** [comment]
I will not block if you guys decide on going to master (adding a comment to update whenever there is a new release)

**Comment by austincunningham** [comment]
> Do we want `master`?? that can bring breaking changes and depend on third party changes.
> 
> I would pin to the fixed version. I know the fix has not been released. Fortunately, they add the binary to the repo. So, we can pin the commit ID or wait for release. [Last release v0.8.0](https://github.com/ekalinin/github-markdown-toc/releases/tag/0.8.0) happened on `Sep 5, 2021`. The, what I would do is pin to the commit having the fix. Additionally, add a comment to update when a new release is available.
> 
> ```diff
> diff --git a/Makefile b/Makefile
> index 356a92ca..4f51f0e0 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -132,7 +132,7 @@ go-bindata: $(GO_BINDATA)
>  GH-MD-TOC=$(PROJECT_PATH)/bin/gh-md-toc
>  $(GH-MD-TOC):
>         mkdir -p $(PROJECT_PATH)/bin
> -       curl -sSL https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0.8.0/gh-md-toc -o $(GH-MD-TOC)
> +       curl -sSL https://raw.githubusercontent.com/ekalinin/github-markdown-toc/c836e5e534f714385beb3c7471438d79a6fddbb4/gh-md-toc -o $(GH-MD-TOC)
>         chmod +x $(GH-MD-TOC)
>  
>  .PHONY: gh-md-toc
> ```

I'm easy I agree I think tying to a commit would be more stable .

**Review by eguzki — APPROVED** [review]

**Pull request merged**
