### PR TITLE
Bump release 2.12

### PR DESCRIPTION
**Pull request by eguzki**
* operator version bump: 0.9.0
* upgrade procedure reset

### CODE REVIEW

**Comment by miguelsorianod** [comment]
The following lines should be removed as they were a procedure specific to the 2.11 release that had to be done at the same time as the backend-redis DeploymentConfig update:
https://github.com/3scale/3scale-operator/blob/d0f1f208b3cc039398a0a61026057233a8ae2de3/pkg/3scale/amp/operator/upgrade.go#L280-L290

Same applies to:
https://github.com/3scale/3scale-operator/blob/d0f1f208b3cc039398a0a61026057233a8ae2de3/pkg/3scale/amp/operator/upgrade.go#L331-L341

The following methods could be removed too as they were specific to 2.11:
* `ensureRedisCommand`
* `ensureRedisPodTemplateLabels`
* `upgradeBackendCronDeploymentConfigMemoryLimits`
* `ensureBackendCronMemoryLimit`
* `backendCronResourcesOverriden`

**Review by miguelsorianod — CHANGES_REQUESTED** [review]
See previous comment

**Comment by eguzki** [comment]
requested changes applied

**Review by miguelsorianod — APPROVED** [review]
:+1:

**Pull request merged**
