### PR TITLE
THREESCALE-10392 Migrate zync DeploymentConfigs to Deployments

### PR DESCRIPTION
**Pull request by carlkyrillos**
# Issue link
JIRA: [THREESCALE-10392](https://issues.redhat.com/browse/THREESCALE-10392)

# What
This PR replaces the `zync`, `zync-que`, and `zync-database` DeploymentConfigs with Deployments.

# Verification steps
1. Provision a cluster
2. Install 3scale locally using master
3. Checkout this PR
4. Re-run 3scale locally
5. Verify that the new `zync`, `zync-que`, and `zync-database` Deployments are created
6. Verify that the `zync`, `zync-que`, and `zync-database` DeploymentConfigs are deleted once the Deployments report healthy

### CODE REVIEW

**Comment by valerymo** [comment]
checking, meanwhile all looks fine, result of tets:
Screenshot from 2023-12-11 16-02-14

Screenshot from 2023-12-11 16-02-14

**Comment by valerymo** [comment]
Hi @carlkyrillos , it looks good to me. Just wanted to ask, if possible, regarding `Zync*PodTemplateAnnotations`. Is it was part of this PR or maybe some additional improvement? Thank you!

**Comment by carlkyrillos** [comment]
> Hi @carlkyrillos , it looks good to me. Just wanted to ask regarding `Zync*PodTemplateAnnotations`. Is it was part of this PR or maybe some additional improvement? Thank you!

Good question, when we used DeploymentConfigs we were able to manage the image for the Pods by using the DC's `.spec.triggers` field which leveraged the ImageStream objects. However, Deployments don't have `.spec.triggers` so if you want to use the ImageStream objects you need to specify those annotations and then OpenShift will take care of the rest. 

This is a temporary solution though and once we migrate all of the DeploymentConfigs to Deployments we're instead going to manage the images directly. This [comment](https://github.com/3scale/3scale-operator/pull/894#discussion_r1400924437) on a similar PR may help provide more context.

**Review by valerymo — COMMENTED** [review]
it looks good to me. Tests done, working as expected.

**Pull request merged**
