### PR TITLE
THREESCALE-10387 add 4.14 as maxOpenShiftVersion to threescale 2.14

### PR DESCRIPTION
**Pull request by carlkyrillos**
JIRA: [THREESCALE-10387](https://issues.redhat.com/browse/THREESCALE-10387)

Adding 4.14 as maxOpenShiftVersion to 3scale-operator 2.14 stable.

### CODE REVIEW

**Comment by eguzki** [comment]
Just heads up that this is missing `com.redhat.openshift.versions: v4.11-v4.14`. Tried here without luck https://github.com/3scale/3scale-operator/pull/877

With this, we still would need to add that label in midstream. The annotation would already be covered.

**Comment by MStokluska** [comment]
> Just heads up that this is missing the label `com.redhat.openshift.versions: v4.11-v4.14`. Tried here without luck #877
> 
> With this, we still would need to add that label in midstream. The annotation would already be covered.

Thanks Eguzki, yes, that flag is already in midstream.

**Comment by eguzki** [comment]
> > Just heads up that this is missing the label `com.redhat.openshift.versions: v4.11-v4.14`. Tried here without luck #877
> > With this, we still would need to add that label in midstream. The annotation would already be covered.
> 
> Thanks Eguzki, yes, that flag is already in midstream.

I know :) My point was we cannot remove that label from midstream, yet.

**Pull request merged**
