### PR TITLE
License_finder check and licenses.xml generation

### PR DESCRIPTION
**Pull request by eguzki**
Two new targets in the makefile:

```
 licenses.xml: Generate licenses.xml file
 licenses-check: Check license compliance of dependencies
```
Added check for licenses in CircleCI workflow for operators.

### CODE REVIEW

**Comment by eguzki** [comment]
we need approval for the following dependencies with their licenses:

```
$ make licenses-check
Checking license compliance
license_finder --decisions-file=/home/eguzki/data/Lanak/redhat/githome/3scale-operator/src/github.com/3scale/3scale-operator/doc/dependency_decisions.yml
LicenseFinder::GoModules: is active
LicenseFinder::Go15VendorExperiment: is active

Dependencies that need approval:
github.com/davecgh/go-spew, v1.1.1, ISC
github.com/hashicorp/golang-lru, v0.5.0, "Mozilla Public License 2.0"
github.com/hashicorp/hcl, v1.0.0, "Mozilla Public License 2.0"
github.com/luci/go-render, v0.0.0-20160219211803-9a04cc21af0f, unknown
github.com/magiconair/properties, v1.8.0, unknown
github.com/pmezard/go-difflib, v1.0.0, unknown
github.com/sergi/go-diff, v1.0.0, unknown
```

**Comment by eguzki** [comment]
@jmprusi this might be useful for the ostia operator as well, as many libraries from 3scale operator and ostia operator should match

**Comment by jmprusi** [comment]
@eguzki yes! Thanks!

**Comment by eguzki** [comment]
@miguelsorianod ready for review and merge

**Pull request merged**
