### PR TITLE
Remove unnecessary graphs on System Grafana

### PR DESCRIPTION
**Pull request by mayorova**
There are some graphs or elements that are not needed:

* `rails_db_runtime_` were removed in https://github.com/3scale/porta/pull/3555
* Those that use `controller='notifications'`, `controller='tenants'`, `controller='status/live'`, `controller='status/ready'` are actually absolutely useless, as there are no such controllers :) It seems to be just copy-paste from the Zync dashboard, where these are actual controllers names.

### CODE REVIEW

**Comment by MStokluska** [comment]
hey @mayorova , thanks. Can you ensure that you are using go 1.19 when running the `make generate` command. 
Changes to bindata coming from this PR seem to me like you are running an older version possibly. 

if not, I can push a commit to this PR with fix to bindata.

**Comment by mayorova** [comment]
Ah, good point, thanks for the tip @MStokluska 
Let me try checking/upgrading Go...

**Comment by mayorova** [comment]
So I actually was running Go 1.20, but downgrading to 1.19 didn't fix the issue.

It is really really weird, because depending on the command I run the output of the **commented** lines is different.

So, I ended up fixing this space _manually_, because I still don't know what was wrong :shrug: 

```
- //Package assets generated by go-bindata.// sources:
+//Package assets generated by go-bindata.// sources:
```

**Review by austincunningham — APPROVED** [review]
/lgtm

**Pull request merged**
