### PR TITLE
THREESCALE-10391 Migrate system DeploymentConfigs to Deployments

### PR DESCRIPTION
**Pull request by carlkyrillos**
# Issue link
JIRA: [THREESCALE-10391](https://issues.redhat.com/browse/THREESCALE-10391)

# What
This PR replaces the `system-app`, `zync-que`, and `zync-database` DeploymentConfigs with Deployments.

# Verification steps
1. Provision a cluster
2. Install 3scale locally using master
3. Checkout this PR
4. Re-run 3scale locally
5. Verify that the new `system-app`, `system-sidekiq`, and `system-searchd` Deployments are created
6. Verify that the `system-app`, `system-sidekiq`, and `system-searchd` DeploymentConfigs are deleted once the Deployments report healthy
    * **NOTE:** The `system-searchd` DeploymentConfig will be deleted before the `system-searchd` Deployment is healthy in order to let the Deployment bind to the `system-searchd` PersistentVolume

### CODE REVIEW

**Comment by austincunningham** [comment]
## Verification
before the running on your branch
```bash
oc get dc
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
apicast-production   1          1         1         config,image(amp-apicast:2.14)
apicast-staging      1          1         1         config,image(amp-apicast:2.14)
backend-listener     1          1         1         config,image(amp-backend:2.14)
backend-redis        1          1         1         config,image(backend-redis:2.14)
backend-worker       1          1         1         config,image(amp-backend:2.14)
system-app           1          1         1         config,image(amp-system:2.14)
system-memcache      1          1         1         config,image(system-memcached:2.14)
system-mysql         1          1         1         config,image(system-mysql:2.14)
system-redis         1          1         1         config,image(system-redis:2.14)
system-searchd       1          1         1         config,image(system-searchd:2.14)
system-sidekiq       1          1         1         config,image(amp-system:2.14)
zync                 1          1         1         config,image(amp-zync:2.14)
zync-database        1          1         1         config,image(zync-database-postgresql:2.14)
zync-que             1          1         1         config,image(amp-zync:2.14)
```
after install kicked off
```bash
➜  oc get deploy
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
backend-cron       1/1     1            1           24s
backend-listener   0/1     1            0           21s
➜  cloudredhatcom oc get deploy
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
backend-cron       1/1     1            1           3m29s
backend-listener   1/1     1            1           3m26s
backend-worker     1/1     1            1           2m45s
system-app         1/1     1            1           92s
system-memcache    1/1     1            1           2m40s
system-searchd     1/1     1            1           2m6s
system-sidekiq     1/1     1            1           2m5s
zync               1/1     1            1           2m4s
zync-database      1/1     1            1           10s
zync-que           1/1     1            1           13s
➜  oc get dc
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
apicast-production   1          1         1         config,image(amp-apicast:2.14)
apicast-staging      1          1         1         config,image(amp-apicast:2.14)
backend-redis        1          1         1         config,image(backend-redis:2.14)
system-mysql         1          1         1         config,image(system-mysql:2.14)
system-redis         1          1         1         config,image(system-redis:2.14)
➜  oc get apimanager -oyaml | yq '.items[].status'
conditions:
  - lastTransitionTime: "2024-01-22T09:06:34Z"
    status: "False"
    type: Available
deployments:
  ready:
    - apicast-production
    - apicast-staging
    - backend-cron
    - backend-listener
    - backend-worker
    - system-app
    - system-memcache
    - system-searchd
    - system-sidekiq
    - zync
    - zync-database
    - zync-que
➜  oc get routes
NAME      HOST/PORT                                           PATH   SERVICES           PORT   TERMINATION   WILDCARD
backend   backend-3scale.apps.aucunnin.xcze.s1.devshift.org          backend-listener   http   edge/Allow    None

```
Wanted to check the installation wizard but 
Looks like an issue with the routes not coming up ??

**Comment by valerymo** [comment]
Hi @carlkyrillos , @austincunningham  I tried test as following

- In first terminal:

```yaml
$ git switch -c THREESCALE-10391 carl/THREESCALE-10391
$ make install
$ oc new-project 3scale-test
$ make download
$ make run
```

- In second terminal:
```yaml
[vmogilev@vmogilev THREESCALE-10391]$ oc apply -f s3-creds-secret.yaml 
secret/s3-credentials created

[vmogilev@vmogilev THREESCALE-10391]$ oc apply -f apimanagerCR.yaml 

apimanager.apps.3scale.net/example-apimanager created
[vmogilev@vmogilev THREESCALE-10391]$ oc get dc
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME            REVISION   DESIRED   CURRENT   TRIGGERED BY
backend-redis   1          1         1         config,image(backend-redis:2.14)
system-mysql    1          1         1         config,image(system-mysql:2.14)
system-redis    1          1         1         config,image(system-redis:2.14)

[vmogilev@vmogilev THREESCALE-10391]$ oc get deploy
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
apicast-production   1/1     1            1           84m
apicast-staging      1/1     1            1           84m
backend-cron         1/1     1            1           84m
backend-listener     1/1     1            1           84m
backend-worker       1/1     1            1           84m
system-app           1/1     1            1           82m
system-memcache      1/1     1            1           84m
system-searchd       1/1     1            1           84m
system-sidekiq       1/1     1            1           84m
zync                 1/1     1            1           84m
zync-database        1/1     1            1           84m
zync-que             1/1     1            1           84m

[vmogilev@vmogilev THREESCALE-10391]$ oc get pod
NAME                                  READY   STATUS      RESTARTS      AGE
apicast-production-66d9bd4c59-8l8j8   1/1     Running     0             84m
apicast-staging-75459f9cf4-5fdhm      1/1     Running     0             84m
backend-cron-78cdb8b55c-k7djj         1/1     Running     0             84m
backend-listener-69ddd85b66-gtgvt     1/1     Running     0             84m
backend-redis-1-deploy                0/1     Completed   0             84m
backend-redis-1-smcl4                 1/1     Running     0             84m
backend-worker-5bccd8c56b-qz8kq       1/1     Running     0             84m
system-app-89d79d455-7rbj2            3/3     Running     0             82m
system-app-post-bbh6m                 0/1     Completed   0             81m
system-app-pre-8vw5t                  0/1     Error       0             84m
system-app-pre-dcfrj                  0/1     Completed   0             83m
system-app-pre-jmls8                  0/1     Error       0             83m
system-memcache-7f4bcc8fdd-tpqh7      1/1     Running     0             84m
system-mysql-1-deploy                 0/1     Completed   0             84m
system-mysql-1-mcfz4                  1/1     Running     0             84m
system-redis-1-deploy                 0/1     Completed   0             84m
system-redis-1-vb226                  1/1     Running     0             84m
system-searchd-8bf59c959-d42pn        1/1     Running     0             84m
system-sidekiq-68b5587f76-8w9jc       1/1     Running     0             84m
zync-database-59d786fc97-vjnnw        1/1     Running     0             84m
zync-db45b55bb-5gchn                  1/1     Running     0             84m
zync-que-6cc5c5fbb5-pphwc             1/1     Running     2 (84m ago)   84m

[vmogilev@vmogilev THREESCALE-10391]$ oc get route
NAME                         HOST/PORT                                                       PATH   SERVICES             PORT      TERMINATION     WILDCARD
backend                      backend-3scale.apps.vmo01.7xu7.s1.devshift.org                         backend-listener     http      edge/Allow      None
zync-3scale-api-rhdp2        api-3scale-apicast-production.apps.vmo01.7xu7.s1.devshift.org          apicast-production   gateway   edge/Redirect   None
zync-3scale-api-zgblj        api-3scale-apicast-staging.apps.vmo01.7xu7.s1.devshift.org             apicast-staging      gateway   edge/Redirect   None
zync-3scale-master-qcncb     master.apps.vmo01.7xu7.s1.devshift.org                                 system-master        http      edge/Redirect   None
zync-3scale-provider-mttft   3scale.apps.vmo01.7xu7.s1.devshift.org                                 system-developer     http      edge/Redirect   None
zync-3scale-provider-sddkp   3scale-admin.apps.vmo01.7xu7.s1.devshift.org                           system-provider      http      edge/Redirect   None
[vmogilev@vmogilev THREESCALE-10391]$ 
```

**Note** Errors in system-app-pre. I repeted test twice. Same. If delete pod  - it's recreated correctly (it just for info, as I'm not sure if make sense, as it's "pre")
`                  openshift.io/scc: restricted-v2
                  seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:           Failed
IP:               10.130.2.64
IPs:
  IP:           10.130.2.64
Controlled By:  Job/system-app-pre
Containers:
  system-app-pre:
    Container ID:  cri-o://132749ee69e6a400c971c50e76417fcbfad6284e02271331b31a04bc746e8f2d
    Image:         quay.io/3scale/porta:latest
    Image ID:      quay.io/3scale/porta@sha256:4ed8b6f628e026853346d5a49348ddb7fc47ef00f9ef46ceb85d90a36972597d
    Port:          <none>
    Host Port:     <none>
    Args:
      bash
      -c
      bundle exec rake boot openshift:deploy
    State:          Terminated
      Reason:       Error
`

**Comment by valerymo** [comment]
# Migration scenario test results
<details>

[vmogilev@vmogilev 3scale-operator] (THREESCALE-10391)$ oc get deploy
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
apicast-production   1/1     1            1           10m
apicast-staging      1/1     1            1           10m
backend-cron         1/1     1            1           14m
backend-listener     1/1     1            1           14m
backend-worker       1/1     1            1           13m
system-app           1/1     1            1           11m
system-memcache      1/1     1            1           13m
system-searchd       1/1     1            1           13m
system-sidekiq       1/1     1            1           13m
zync                 1/1     1            1           13m
zync-database        1/1     1            1           11m
zync-que             1/1     1            1           11m
[vmogilev@vmogilev 3scale-operator] (THREESCALE-10391)$ oc get dc
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME            REVISION   DESIRED   CURRENT   TRIGGERED BY
backend-redis   1          1         1         config,image(backend-redis:2.14)
system-mysql    1          1         1         config,image(system-mysql:2.14)
system-redis    1          1         1         config,image(system-redis:2.14)
[vmogilev@vmogilev 3scale-operator] (THREESCALE-10391)$ oc get pod
NAME                                  READY   STATUS      RESTARTS        AGE
apicast-production-668cb6d9cf-s79qb   1/1     Running     0               10m
apicast-staging-559fb5d94f-w5zlz      1/1     Running     0               11m
backend-cron-78cdb8b55c-pgj42         1/1     Running     0               14m
backend-listener-69ddd85b66-2n6cc     1/1     Running     0               14m
backend-redis-1-74w2t                 1/1     Running     0               24m
backend-redis-1-deploy                0/1     Completed   0               24m
backend-worker-5bccd8c56b-5sxhd       1/1     Running     0               13m
system-app-755b4f94b7-47mh8           3/3     Running     0               11m
system-app-post-s7l4c                 0/1     Completed   0               10m
system-app-pre-zmbvh                  0/1     Completed   0               13m
system-memcache-7f4bcc8fdd-5v7jr      1/1     Running     0               13m
system-mysql-1-bw6wv                  1/1     Running     0               24m
system-mysql-1-deploy                 0/1     Completed   0               24m
system-redis-1-deploy                 0/1     Completed   0               24m
system-redis-1-xb5ld                  1/1     Running     0               24m
system-searchd-8bf59c959-hsk4d        1/1     Running     0               11m
system-sidekiq-68b7f9ff76-92b2x       1/1     Running     0               13m
zync-database-59d786fc97-sztjh        1/1     Running     0               11m
zync-db45b55bb-6lbmv                  1/1     Running     1 (9m ago)      13m
zync-que-6cc5c5fbb5-6qrc4             1/1     Running     4 (9m41s ago)   11m
[vmogilev@vmogilev 3scale-operator] (THREESCALE-10391)$ oc get job
NAME              COMPLETIONS   DURATION   AGE
system-app-post   1/1           13s        10m
system-app-pre    1/1           12s        13m
[vmogilev@vmogilev 3scale-operator] (THREESCALE-10391)$ oc get route
NAME                         HOST/PORT                                                       PATH   SERVICES             PORT      TERMINATION     WILDCARD
backend                      backend-3scale.apps.vmo01.7xu7.s1.devshift.org                         backend-listener     http      edge/Allow      None
zync-3scale-api-t8vck        api-3scale-apicast-production.apps.vmo01.7xu7.s1.devshift.org          apicast-production   gateway   edge/Redirect   None
zync-3scale-api-wgnqh        api-3scale-apicast-staging.apps.vmo01.7xu7.s1.devshift.org             apicast-staging      gateway   edge/Redirect   None
zync-3scale-master-k8phh     master.apps.vmo01.7xu7.s1.devshift.org                                 system-master        http      edge/Redirect   None
zync-3scale-provider-49n8z   3scale.apps.vmo01.7xu7.s1.devshift.org                                 system-developer     http      edge/Redirect   None
zync-3scale-provider-5v4xm   3scale-admin.apps.vmo01.7xu7.s1.devshift.org                           system-provider      http      edge/Redirect   None
[vmogilev@vmogilev 3scale-operator] (THREESCALE-10391)$ 
</details>

# Migration scenario test results
<details>

[vmogilev@vmogilev THREESCALE-10391]$ 
[vmogilev@vmogilev THREESCALE-10391]$ oc get deploy
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
apicast-production   1/1     1            1           4m45s
apicast-staging      1/1     1            1           4m45s
backend-cron         1/1     1            1           4m50s
backend-listener     1/1     1            1           4m50s
backend-worker       1/1     1            1           4m49s
system-app           1/1     1            1           2m44s
system-memcache      1/1     1            1           4m48s
system-searchd       1/1     1            1           4m48s
system-sidekiq       1/1     1            1           4m46s
zync                 1/1     1            1           4m46s
zync-database        1/1     1            1           4m46s
zync-que             1/1     1            1           4m46s
[vmogilev@vmogilev THREESCALE-10391]$ 
[vmogilev@vmogilev THREESCALE-10391]$ oc get dc
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME            REVISION   DESIRED   CURRENT   TRIGGERED BY
backend-redis   1          1         1         config,image(backend-redis:2.14)
system-mysql    1          1         1         config,image(system-mysql:2.14)
system-redis    1          1         1         config,image(system-redis:2.14)
[vmogilev@vmogilev THREESCALE-10391]$ 
[vmogilev@vmogilev THREESCALE-10391]$ 
[vmogilev@vmogilev THREESCALE-10391]$ oc get route
NAME                         HOST/PORT                                                       PATH   SERVICES             PORT      TERMINATION     WILDCARD
backend                      backend-3scale.apps.vmo01.7xu7.s1.devshift.org                         backend-listener     http      edge/Allow      None
zync-3scale-api-jrzx7        api-3scale-apicast-production.apps.vmo01.7xu7.s1.devshift.org          apicast-production   gateway   edge/Redirect   None
zync-3scale-api-pv5nj        api-3scale-apicast-staging.apps.vmo01.7xu7.s1.devshift.org             apicast-staging      gateway   edge/Redirect   None
zync-3scale-master-srpxq     master.apps.vmo01.7xu7.s1.devshift.org                                 system-master        http      edge/Redirect   None
zync-3scale-provider-4djq2   3scale.apps.vmo01.7xu7.s1.devshift.org                                 system-developer     http      edge/Redirect   None
zync-3scale-provider-k4hj6   3scale-admin.apps.vmo01.7xu7.s1.devshift.org                           system-provider      http      edge/Redirect   None
[vmogilev@vmogilev THREESCALE-10391]$ oc get pod
NAME                                  READY   STATUS      RESTARTS        AGE
apicast-production-668cb6d9cf-pfpln   1/1     Running     0               5m2s
apicast-staging-559fb5d94f-w74cg      1/1     Running     0               5m2s
backend-cron-78cdb8b55c-vlwbk         1/1     Running     0               5m7s
backend-listener-69ddd85b66-lbj94     1/1     Running     0               5m6s
backend-redis-1-deploy                0/1     Completed   0               5m6s
backend-redis-1-pxdt6                 1/1     Running     0               5m6s
backend-worker-5bccd8c56b-c7bhs       1/1     Running     0               5m6s
system-app-755b4f94b7-tmb95           3/3     Running     0               3m1s
system-app-post-j4dtm                 0/1     Completed   0               88s
system-app-pre-9c756                  0/1     Completed   0               4m14s
system-app-pre-mkhw6                  0/1     Error       0               5m3s
system-app-pre-scdsv                  0/1     Error       0               4m43s
system-memcache-7f4bcc8fdd-26d7d      1/1     Running     0               5m2s
system-mysql-1-deploy                 0/1     Completed   0               5m7s
system-mysql-1-dk4n2                  1/1     Running     0               5m6s
system-redis-1-deploy                 0/1     Completed   0               5m7s
system-redis-1-zlk6g                  1/1     Running     0               5m6s
system-searchd-8bf59c959-f6q2x        1/1     Running     0               5m5s
system-sidekiq-68b7f9ff76-zdk98       1/1     Running     0               5m3s
zync-database-59d786fc97-lmfbz        1/1     Running     0               5m3s
zync-db45b55bb-rv6bz                  1/1     Running     0               5m3s
zync-que-6cc5c5fbb5-ltzdv             1/1     Running     2 (4m54s ago)   5m3s
[vmogilev@vmogilev THREESCALE-10391]$ 
[vmogilev@vmogilev THREESCALE-10391]$ 
[vmogilev@vmogilev THREESCALE-10391]$ oc describe pod system-app-pre-mkhw6
Name:             system-app-pre-mkhw6
Namespace:        3scale-test
Priority:         0
Service Account:  amp
Node:             ip-10-0-58-100.eu-west-1.compute.internal/10.0.58.100
Start Time:       Tue, 23 Jan 2024 19:08:54 +0200
Labels:           batch.kubernetes.io/controller-uid=cf6e0bad-464d-42ff-bb2d-e0433e028349
                  batch.kubernetes.io/job-name=system-app-pre
                  controller-uid=cf6e0bad-464d-42ff-bb2d-e0433e028349
                  job-name=system-app-pre
Annotations:      k8s.ovn.org/pod-networks:
                    {"default":{"ip_addresses":["10.130.2.92/23"],"mac_address":"0a:58:0a:82:02:5c","gateway_ips":["10.130.2.1"],"routes":[{"dest":"10.128.0.0...
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "ovn-kubernetes",
                        "interface": "eth0",
                        "ips": [
                            "10.130.2.92"
                        ],
                        "mac": "0a:58:0a:82:02:5c",
                        "default": true,
                        "dns": {}
                    }]
                  openshift.io/scc: restricted-v2
                  seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:           Failed
IP:               10.130.2.92
IPs:
  IP:           10.130.2.92
Controlled By:  Job/system-app-pre
Containers:
  system-app-pre:
    Container ID:  cri-o://766a0a76a16c452bfbe8a838064f1d23506289dabaef602c8fba98a4370fabbd
    Image:         quay.io/3scale/porta:latest
    Image ID:      quay.io/3scale/porta@sha256:4ed8b6f628e026853346d5a49348ddb7fc47ef00f9ef46ceb85d90a36972597d
    Port:          <none>
    Host Port:     <none>
    Args:
      bash
      -c
      bundle exec rake boot openshift:deploy
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 23 Jan 2024 19:08:55 +0200
      Finished:     Tue, 23 Jan 2024 19:09:04 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  800Mi
    Requests:
      cpu:     50m
      memory:  600Mi
    Environment:
      APICAST_REGISTRY_URL:                          <set to the key 'APICAST_REGISTRY_URL' of config map 'system-environment'>                          Optional: false
      FILE_UPLOAD_STORAGE:                           <set to the key 'FILE_UPLOAD_STORAGE' of config map 'system-environment'>                           Optional: false
      FORCE_SSL:                                     <set to the key 'FORCE_SSL' of config map 'system-environment'>                                     Optional: false
      PROVIDER_PLAN:                                 <set to the key 'PROVIDER_PLAN' of config map 'system-environment'>                                 Optional: false
      RAILS_ENV:                                     <set to the key 'RAILS_ENV' of config map 'system-environment'>                                     Optional: false
      RAILS_LOG_LEVEL:                               <set to the key 'RAILS_LOG_LEVEL' of config map 'system-environment'>                               Optional: false
      RAILS_LOG_TO_STDOUT:                           <set to the key 'RAILS_LOG_TO_STDOUT' of config map 'system-environment'>                           Optional: false
      SSL_CERT_DIR:                                  <set to the key 'SSL_CERT_DIR' of config map 'system-environment'>                                  Optional: false
      THINKING_SPHINX_PORT:                          <set to the key 'THINKING_SPHINX_PORT' of config map 'system-environment'>                          Optional: false
      THREESCALE_SANDBOX_PROXY_OPENSSL_VERIFY_MODE:  <set to the key 'THREESCALE_SANDBOX_PROXY_OPENSSL_VERIFY_MODE' of config map 'system-environment'>  Optional: false
      THREESCALE_SUPERDOMAIN:                        <set to the key 'THREESCALE_SUPERDOMAIN' of config map 'system-environment'>                        Optional: false
      DATABASE_URL:                                  <set to the key 'URL' in secret 'system-database'>                                                  Optional: false
      MASTER_DOMAIN:                                 <set to the key 'MASTER_DOMAIN' in secret 'system-seed'>                                            Optional: false
      MASTER_USER:                                   <set to the key 'MASTER_USER' in secret 'system-seed'>                                              Optional: false
      MASTER_PASSWORD:                               <set to the key 'MASTER_PASSWORD' in secret 'system-seed'>                                          Optional: false
      ADMIN_ACCESS_TOKEN:                            <set to the key 'ADMIN_ACCESS_TOKEN' in secret 'system-seed'>                                       Optional: false
      USER_LOGIN:                                    <set to the key 'ADMIN_USER' in secret 'system-seed'>                                               Optional: false
      USER_PASSWORD:                                 <set to the key 'ADMIN_PASSWORD' in secret 'system-seed'>                                           Optional: false
      USER_EMAIL:                                    <set to the key 'ADMIN_EMAIL' in secret 'system-seed'>                                              Optional: false
      TENANT_NAME:                                   <set to the key 'TENANT_NAME' in secret 'system-seed'>                                              Optional: false
      THINKING_SPHINX_ADDRESS:                       system-searchd
      EVENTS_SHARED_SECRET:                          <set to the key 'PASSWORD' in secret 'system-events-hook'>                 Optional: false
      RECAPTCHA_PUBLIC_KEY:                          <set to the key 'PUBLIC_KEY' in secret 'system-recaptcha'>                 Optional: false
      RECAPTCHA_PRIVATE_KEY:                         <set to the key 'PRIVATE_KEY' in secret 'system-recaptcha'>                Optional: false
      SECRET_KEY_BASE:                               <set to the key 'SECRET_KEY_BASE' in secret 'system-app'>                  Optional: false
      MEMCACHE_SERVERS:                              <set to the key 'SERVERS' in secret 'system-memcache'>                     Optional: false
      REDIS_URL:                                     <set to the key 'URL' in secret 'system-redis'>                            Optional: false
      REDIS_NAMESPACE:                               <set to the key 'NAMESPACE' in secret 'system-redis'>                      Optional: false
      REDIS_SENTINEL_HOSTS:                          <set to the key 'SENTINEL_HOSTS' in secret 'system-redis'>                 Optional: false
      REDIS_SENTINEL_ROLE:                           <set to the key 'SENTINEL_ROLE' in secret 'system-redis'>                  Optional: false
      BACKEND_REDIS_URL:                             <set to the key 'REDIS_STORAGE_URL' in secret 'backend-redis'>             Optional: false
      BACKEND_REDIS_SENTINEL_HOSTS:                  <set to the key 'REDIS_STORAGE_SENTINEL_HOSTS' in secret 'backend-redis'>  Optional: false
      BACKEND_REDIS_SENTINEL_ROLE:                   <set to the key 'REDIS_STORAGE_SENTINEL_ROLE' in secret 'backend-redis'>   Optional: false
      BACKEND_URL:                                   <set to the key 'service_endpoint' in secret 'backend-listener'>           Optional: false
      BACKEND_PUBLIC_URL:                            <set to the key 'route_endpoint' in secret 'backend-listener'>             Optional: false
      SMTP_ADDRESS:                                  <set to the key 'address' in secret 'system-smtp'>                         Optional: false
      SMTP_USER_NAME:                                <set to the key 'username' in secret 'system-smtp'>                        Optional: false
      SMTP_PASSWORD:                                 <set to the key 'password' in secret 'system-smtp'>                        Optional: false
      SMTP_DOMAIN:                                   <set to the key 'domain' in secret 'system-smtp'>                          Optional: false
      SMTP_PORT:                                     <set to the key 'port' in secret 'system-smtp'>                            Optional: false
      SMTP_AUTHENTICATION:                           <set to the key 'authentication' in secret 'system-smtp'>                  Optional: false
      SMTP_OPENSSL_VERIFY_MODE:                      <set to the key 'openssl.verify.mode' in secret 'system-smtp'>             Optional: false
      APICAST_ACCESS_TOKEN:                          <set to the key 'ACCESS_TOKEN' in secret 'system-master-apicast'>          Optional: false
      ZYNC_AUTHENTICATION_TOKEN:                     <set to the key 'ZYNC_AUTHENTICATION_TOKEN' in secret 'zync'>              Optional: false
      CONFIG_INTERNAL_API_USER:                      <set to the key 'username' in secret 'backend-internal-api'>               Optional: false
      CONFIG_INTERNAL_API_PASSWORD:                  <set to the key 'password' in secret 'backend-internal-api'>               Optional: false
      AWS_BUCKET:                                    <set to the key 'AWS_BUCKET' in secret 's3-credentials'>                   Optional: false
      AWS_REGION:                                    <set to the key 'AWS_REGION' in secret 's3-credentials'>                   Optional: false
      AWS_PROTOCOL:                                  <set to the key 'AWS_PROTOCOL' in secret 's3-credentials'>                 Optional: true
      AWS_HOSTNAME:                                  <set to the key 'AWS_HOSTNAME' in secret 's3-credentials'>                 Optional: true
      AWS_PATH_STYLE:                                <set to the key 'AWS_PATH_STYLE' in secret 's3-credentials'>               Optional: true
      AWS_ACCESS_KEY_ID:                             <set to the key 'AWS_ACCESS_KEY_ID' in secret 's3-credentials'>            Optional: false
      AWS_SECRET_ACCESS_KEY:                         <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 's3-credentials'>        Optional: false
      MASTER_ACCESS_TOKEN:                           <set to the key 'MASTER_ACCESS_TOKEN' in secret 'system-seed'>             Optional: false
      ORACLE_SYSTEM_PASSWORD:                        <set to the key 'ORACLE_SYSTEM_PASSWORD' in secret 'system-database'>      Optional: true
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qsr5v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  system-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      system
    Optional:  false
  kube-api-access-qsr5v:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       5m23s                  default-scheduler  Successfully assigned 3scale-test/system-app-pre-mkhw6 to ip-10-0-58-100.eu-west-1.compute.internal
  Normal   AddedInterface  5m23s                  multus             Add eth0 [10.130.2.92/23] from ovn-kubernetes
  Warning  Failed          5m23s (x2 over 5m23s)  kubelet            Error: secret "zync" not found
  Normal   Pulled          5m22s (x3 over 5m23s)  kubelet            Container image "quay.io/3scale/porta:latest" already present on machine
  Normal   Created         5m22s                  kubelet            Created container system-app-pre
  Normal   Started         5m22s                  kubelet            Started container system-app-pre
[vmogilev@vmogilev THREESCALE-10391]$ 

</details>

**Comment by carlkyrillos** [comment]
> Verification done for 2 scenarios:
> 
> 1. Migration - working as expected. Please see `Migration scenario test results` for details.
> 2. Fresh Install - seems all is working as expected, but there are 2 pods in Error state;
> 
> ```
> $ oc get pod |grep Err
> system-app-pre-mkhw6                  0/1     Error       0             14m
> system-app-pre-scdsv                  0/1     Error       0             14m
> ```
> 
> Please see details in `Fresh install test results` section
> 
> ## Migration scenario test results
> ## Fresh install test results

Thank you for the in-depth review @valerymo . In general I think it's okay if the prehook Job pods are failing occasionally as long as it eventually succeeds. My guess is they are failing on fresh install because the database DCs haven't been migrated yet - will be addressed in [THREESCALE-10393](https://issues.redhat.com/browse/THREESCALE-10393).

**Review by austincunningham — APPROVED** [review]
Yep redid the verification and confirmed that the routes are now present
```bash
➜  ~ oc get dc
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
apicast-production   1          1         1         config,image(amp-apicast:2.14)
apicast-staging      1          1         1         config,image(amp-apicast:2.14)
backend-cron         1          1         1         config,image(amp-backend:2.14)
backend-listener     1          1         1         config,image(amp-backend:2.14)
backend-redis        1          1         1         config,image(backend-redis:2.14)
backend-worker       1          1         1         config,image(amp-backend:2.14)
system-app           1          1         1         config,image(amp-system:2.14)
system-memcache      1          1         1         config,image(system-memcached:2.14)
system-mysql         1          1         1         config,image(system-mysql:2.14)
system-redis         1          1         1         config,image(system-redis:2.14)
system-searchd       1          1         1         config,image(system-searchd:2.14)
system-sidekiq       1          1         1         config,image(amp-system:2.14)
zync                 1          1         1         config,image(amp-zync:2.14)
zync-database        1          1         1         config,image(zync-database-postgresql:2.14)
zync-que             1          1         1         config,image(amp-zync:2.14)
➜  ~ oc get deploy
No resources found in 3scale-test namespace.
➜  ~ oc get routes
NAME                         HOST/PORT                                                          PATH   SERVICES             PORT      TERMINATION     WILDCARD
backend                      backend-3scale.apps.aucunnin.ip84.s1.devshift.org                         backend-listener     http      edge/Allow      None
zync-3scale-api-l4d7q        api-3scale-apicast-production.apps.aucunnin.ip84.s1.devshift.org          apicast-production   gateway   edge/Redirect   None
zync-3scale-api-zqxrg        api-3scale-apicast-staging.apps.aucunnin.ip84.s1.devshift.org             apicast-staging      gateway   edge/Redirect   None
zync-3scale-master-jq642     master.apps.aucunnin.ip84.s1.devshift.org                                 system-master        http      edge/Redirect   None
zync-3scale-provider-4p9sm   3scale-admin.apps.aucunnin.ip84.s1.devshift.org                           system-provider      http      edge/Redirect   None
zync-3scale-provider-ft8vx   3scale.apps.aucunnin.ip84.s1.devshift.org                                 system-developer     http      edge/Redirect   None
# After upgrade
➜  ~ oc get dc
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME            REVISION   DESIRED   CURRENT   TRIGGERED BY
backend-redis   1          1         1         config,image(backend-redis:2.14)
system-mysql    1          1         1         config,image(system-mysql:2.14)
system-redis    1          1         1         config,image(system-redis:2.14)
➜  ~ oc get deploy
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
apicast-production   1/1     1            1           5m3s
apicast-staging      1/1     1            1           5m34s
backend-cron         1/1     1            1           9m3s
backend-listener     1/1     1            1           8m53s
backend-worker       1/1     1            1           8m22s
system-app           1/1     1            1           5m48s
system-memcache      1/1     1            1           8m18s
system-searchd       1/1     1            1           7m41s
system-sidekiq       1/1     1            1           7m40s
zync                 1/1     1            1           7m39s
zync-database        1/1     1            1           5m45s
zync-que             1/1     1            1           5m48s
➜  ~ oc get routes
NAME                         HOST/PORT                                                          PATH   SERVICES             PORT      TERMINATION     WILDCARD
backend                      backend-3scale.apps.aucunnin.ip84.s1.devshift.org                         backend-listener     http      edge/Allow      None
zync-3scale-api-l4d7q        api-3scale-apicast-production.apps.aucunnin.ip84.s1.devshift.org          apicast-production   gateway   edge/Redirect   None
zync-3scale-api-zqxrg        api-3scale-apicast-staging.apps.aucunnin.ip84.s1.devshift.org             apicast-staging      gateway   edge/Redirect   None
zync-3scale-master-jq642     master.apps.aucunnin.ip84.s1.devshift.org                                 system-master        http      edge/Redirect   None
zync-3scale-provider-4p9sm   3scale-admin.apps.aucunnin.ip84.s1.devshift.org                           system-provider      http      edge/Redirect   None
zync-3scale-provider-ft8vx   3scale.apps.aucunnin.ip84.s1.devshift.org                                 system-developer     http      edge/Redirect   None
```
confirmed the wizard is working as expected :+1:

**Pull request merged**
