### PR TITLE
THREESCALE-10698 Remove remaining DeploymentConfig references

### PR DESCRIPTION
**Pull request by carlkyrillos**
# Issue Link
JIRA: [THREESCALE-10698](https://issues.redhat.com/browse/THREESCALE-10698)

# What
This PR removes or updates several references to DeploymentConfigs in the operator code, docs, and CSV/CRDs. Note that not all references to DeploymentConfigs can be removed at this time because the operator needs to be able to `get` and `delete` them as part of the migration for the upgrade path. These last few references to DeploymentConfigs will need to be removed in a future release (likely 2.16).

# Verification Steps
The main verification for this PR is confirming that the GrafanaDashboards still work on an upgrade path from the master branch as this will also verify the overall functionality of 3scale-operator.

1. Provision a cluster
2. Checkout the master branch
3. Prepare to run the operator locally:
```bash
make install
make download
```
4. Create the Namespace, `s3-credentials` Secret, and the APIManager CR (with .spec.monitoring.enabled = true):
```bash
export NAMESPACE=3scale-test
oc new-project $NAMESPACE

cat << EOF | oc create -f -
kind: Secret
apiVersion: v1
metadata:
  name: s3-credentials
  namespace: $NAMESPACE
data:
  AWS_ACCESS_KEY_ID: c29tZXRoaW5nCg==
  AWS_BUCKET: c29tZXRoaW5nCg==
  AWS_REGION: dXMtd2VzdC0xCg==
  AWS_SECRET_ACCESS_KEY: c29tZXRoaW5nCg==
type: Opaque
EOF

cat << EOF | oc create -f -
kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: 3scale
  namespace: $NAMESPACE
spec:
  monitoring:
    enabled: true
  wildcardDomain: $REPLACE_ME_WITH_WILDCARD_DOMAIN
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: s3-credentials
EOF
```
5. Install the prometheus-operator (Red Hat version) in the `3scale-test` Namespace using the default Update channel (`beta`) and Version(`4.10.0`)
6. Wait for the prometheus-operator to finish installing and then create a Prometheus CR and the required RBAC:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 3scale-prometheus
  namespace: 3scale-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 3scale-prometheus
  namespace: 3scale-test
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 3scale-prometheus
  namespace: 3scale-test
subjects:
  - kind: ServiceAccount
    name: 3scale-prometheus
    namespace: 3scale-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 3scale-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: 3scale-test
spec:
  podMonitorSelector: {}
  ruleSelector: {}
  serviceAccountName: 3scale-prometheus
```
7. Install the grafana-operator (Community version) in the `3scale-test` Namespace using `v4` for the Update channel and `4.10.1` for the Version
8. Wait for the grafana-operator to finish installing and then create a Grafana CR and a GrafanaDataSource CR:
```yaml
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  name: middleware
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-operated:9090
      isDefault: true
      version: 1
      editable: true
      jsonData:
        timeInterval: "5s"
---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example
  namespace: 3scale-test
spec:
  config:
    security:
      admin_password: Password1
      admin_user: admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - 3scale-api-management
```
9. The routes to prometheus and grafana aren't being created by default but you can still access the UI using port forwarding. First run the commands below in separate terminal windows and then access these links in your browser - [grafana](http://127.0.0.1:3000/), [prometheus](http://127.0.0.1:9090/graph):
```bash
oc port-forward services/grafana-service -n 3scale-test 3000:3000
oc port-forward services/prometheus-operated -n 3scale-test 9090:9090
```
10. Run the 3scale-operator locally and wait for 3scale to finish installing:
```bash
make run
```
11. Login into [grafana](http://127.0.0.1:3000/) (username=`admin`, password=`Password1`) and verify the dashboards are present and working
12. Stop running the 3scale-operator, checkout this PR, and run the operator locally again (`make run`)
13. Wait for the upgrade to complete
14. Log back into grafana and verify that the dashboards are still working

### CODE REVIEW

**Comment by austincunningham** [comment]
I think we need to verify the monitoring stack with this one . 

I prepose that we install master with the monitoring enabled and setup and then upgrade with this branch to see if there is any loss of functionality.

**Comment by carlkyrillos** [comment]
> I think we need to verify the monitoring stack with this one .
> 
> I prepose that we install master with the monitoring enabled and setup and then upgrade with this branch to see if there is any loss of functionality.

Yes we will need to verify that the dashboards are still working. I verified this myself during testing and I'll include the steps to confirm this in the verification section.

**Comment by eguzki** [comment]
let doc team know about this change. Official doc is full of references to DEploymentConfigs and, some (hopefully few) `oc` commands reading and patching deploymentconfigs.

**Comment by valerymo** [comment]
Verified. Grafana works as expected. Below are images before and after upgrade.
- On **master** branch:
Screenshot from 2024-02-04 12-42-36

Screenshot from 2024-02-04 12-25-13

- On **THREESCALE-10698** branch
Screenshot from 2024-02-04 12-42-36

Screenshot from 2024-02-04 12-38-21

Screenshot from 2024-02-04 12-24-24

**Comment by valerymo** [comment]
@carlkyrillos I'd like to place /lgtm, as I verified and it's working fine for me, but maybe rebase is needed, as I see two tasks (that I'm familiar) merged already - Tenants params (10525) and Mapping rules (10238). But GitHub does not show conflicts, so I will add my lgtm, and you please decide if you want to rebase. Thank you

**Comment by carlkyrillos** [comment]
> @carlkyrillos I'd like to place /lgtm, as I verified and it's working correct as seems to me (same way for master and PR's branch), but maybe rebase is needed, as I see two tasks (that I'm familiar) merged already - Tenants params (10525) and Mapping rules (10238). But GitHub does not show conflicts, so I will add my lgtm, and you please decide if you want to rebase (if yes, I will retest). Thank you

@valerymo thank you for the review. We can merge this PR now since it's just going to the feature branch but we will need to rebase the feature branch before merging it into master.

**Comment by valerymo** [comment]
> > @carlkyrillos I'd like to place /lgtm, as I verified and it's working correct as seems to me (same way for master and PR's branch), but maybe rebase is needed, as I see two tasks (that I'm familiar) merged already - Tenants params (10525) and Mapping rules (10238). But GitHub does not show conflicts, so I will add my lgtm, and you please decide if you want to rebase (if yes, I will retest). Thank you
> 
> @valerymo thank you for the review. We can merge this PR now since it's just going to the feature branch but we will need to rebase the feature branch before merging it into master.

yes, sure, thanks

**Pull request merged**
