### PR TITLE
Build Zync from ubi8/ruby-27

### PR DESCRIPTION
**Pull request by guicassolato**
Related to https://github.com/3scale/zync/pull/457/commits/a8b830f766a51bbe17d723c3a83b22cbc41303fc
Fixes build error such as https://app.circleci.com/pipelines/github/3scale/3scale-operator/3642/workflows/200d2213-492a-4fa3-a36a-b15232342809/jobs/26702

### CODE REVIEW

**Comment by miguelsorianod** [comment]
Hi @guicassolato 

We already tried this with https://github.com/3scale/3scale-operator/pull/626 but that didn't solve the issue and it seems unrelated, as the images are being built by Zync and not by us.
Although it would fix the build (which we are not going to do anymore) the error seems to be another one.

See the logs provided in THREESCALE-7283

**Comment by guicassolato** [comment]
> Hi @guicassolato
> 
> We already tried this with #626 but that didn't solve the issue and it seems unrelated, as the images are being built by Zync and not by us.

Thanks, @miguelsorianod. I was trying to be proactive here after having been receiving those notifications about the failed builds for a few days in a row.

I am aware of the proposal for each component to be responsible for its own build, which I am completely in favour of. If this work is closer to become a reality as a coordinated effort, and there is no need to fix Zync's build here, then feel free to close the PR, and I'll ignore the notifications from now. AFAIK, so far Zync is not building and pushing nightly to quay yet. (We still rely on this job of the 3scale-operator repo.) But maybe I'm wrong ad we do have something in place, not in Zync upstream, but in Jenkins, by our CI/CD team.

**Comment by guicassolato** [comment]
Closing in favour of #626 or any effort made in that direction of delegating this build to each component, whatever gets merged first :)

**Comment by miguelsorianod** [comment]
Hi @guicassolato,

Thanks. Zync is already being built by Zync team with `latest` tag. See THREESCALE-7142, but it seems there is another unrelated issue not related to build time but to run time. See THREESCALE-7283 for the reported error.

**Comment by guicassolato** [comment]
Thank you, @miguelsorianod. I wasn't aware of https://issues.redhat.com/browse/THREESCALE-7142 and it turns out nightly builds are already configured in quay.io for Zync.

**Pull request closed without merging**
