### PR TITLE
Update 3scale-2.10-stable CI images config

### PR DESCRIPTION
**Pull request by miguelsorianod**
Update images used in CI to 3scale-2.10.0-GA

### CODE REVIEW

**Comment by miguelsorianod** [comment]
We shouldn't merge this until all GA upstream images are available and all CI tests pass

**Comment by miguelsorianod** [comment]
I've rebuilt the images by running the following command in a temporary branch based from the 3scale-2.10-stable branch with CI changes available to run the CircleCI task that generates components images with:
```
 CIRCLE_CI_API_TOKEN=XXX IMAGES_GIT_REF=3scale-2.10.0-GA IMAGES_REMOTE_TAG=3scale-2.10.0-GA make build-3scale-images
```

After running that job the images have been successfully generated and pushed. The CircleCI job with the results can be found in:
https://app.circleci.com/pipelines/github/3scale/3scale-operator/3497/workflows/1d6a312a-3caa-49d2-9279-75f4dc16165a/jobs/25656

However, the images have been pushed to each component repository. I've moved them by pulling them and pushing them to
the '3scale210' quay repository as we have been having for all releases, and removing them from each component repository to clean them and not cause further confusion:
```
$ docker pull quay.io/3scale/apisonator:2.10
$ docker tag quay.io/3scale/apisonator:2.10 quay.io/3scale/3scale210:apisonator-3scale-2.10.0-GA 
$ docker push quay.io/3scale/3scale210:apisonator-3scale-2.10.0-GA
$ docker pull quay.io/3scale/apicast:2.10
$ docker tag quay.io/3scale/apicast:2.10 quay.io/3scale/3scale210:apicast-3scale-2.10.0-GA 
$ docker push quay.io/3scale/3scale210:apicast-3scale-2.10.0-GA
$ docker pull quay.io/3scale/porta:2.10
$ docker tag quay.io/3scale/porta:2.10 quay.io/3scale/3scale210:porta-3scale-2.10.0-GA 
$ docker push quay.io/3scale/3scale210:porta-3scale-2.10.0-GA
$ docker pull quay.io/3scale/zync:2.10
$ docker tag quay.io/3scale/zync:2.10 quay.io/3scale/3scale210:zync-3scale-2.10.0-GA 
$ docker push quay.io/3scale/3scale210:zync-3scale-2.10.0-GA
```

For 3scale 2.11 and future versions we'll have to rethink where do we want to store this images and who would be responsible to generate them.

**Comment by miguelsorianod** [comment]
I've also added a new commit due to the tests were failing because they were trying to get the GA images from each component instead of going to the unified repository. There are several alternatives to fix this:
* Adapt the tests to use the default hardcoded ones in the case of this branch. This is what's been done
* Test using nightly images
* Refactor/update tests to allow defining each component tag AND registry.

I've opted for the first option being the simplest. Given that the generation/management of images will potentially change with the new development methodology it was not worth doing a considerable refactor.

**Comment by miguelsorianod** [comment]
When running the tests I've found the zync 2.10.0 GA image URL had a typo. I've added a new commit to fix it

**Review by eguzki — APPROVED** [review]

**Pull request merged**
